function gwt(){var O='bootstrap',P='begin',Q='gwt.codesvr.gwt=',R='gwt.codesvr=',S='gwt',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='gwt::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='gwt.nocache.js',Ib='base',Jb='//',Kb='app.profile',Lb='display.type',Mb=2,Nb='retina',Ob='normal',Pb='user.agent',Qb='webkit',Rb='safari',Sb='msie',Tb=10,Ub=11,Vb='ie10',Wb=9,Xb='ie9',Yb=8,Zb='ie8',$b='gecko',_b='gecko1_8',ac=3,bc=4,cc='selectingPermutation',dc='gwt.devmode.js',ec='sankhya',fc='182D9857F0E40CB999E381F48EC1121B',gc='jiva',hc='2F95514409D9D63AD7D7466708990B38',ic=':1',jc='362010EA49DBAD7F8EE60727A67867AF',kc='3AD0D80AC42A7589CE9D260F4F9B910C',lc='449E314899EB868F5D2EFBE49166956D',mc='59782DDA49F32B659B65AACB232A67FE',nc='F9BA5550D1E53164171DD4773A8F0359',oc=':',pc='.cache.js',qc='link',rc='rel',sc='stylesheet',tc='href',uc='loadExternalRefs',vc='css/bootstrap-datetimepicker-2.3.1.min.cache.css',wc='css/bootstrap-switch-3.3.2.min.cache.css',xc='css/bootstrap-select-1.6.4.min.cache.css',yc='css/bootstrap-select-fix-1.6.4.min.cache.css',zc='css/card-1.0.0.cache.css',Ac='css/animate-3.2.0.min.cache.css',Bc='css/summernote-0.6.2.min.cache.css',Cc='css/typeahead-0.10.5.min.cache.css',Dc='end',Ec='http:',Fc='file:',Gc='_gwt_dummy_',Hc='__gwtDevModeHook:gwt',Ic='Ignoring non-whitelisted Dev Mode URL: ',Jc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
gwt.__sendStats=r;gwt.__moduleName=S;gwt.__errFn=null;gwt.__moduleBase=U;gwt.__softPermutationId=V;gwt.__computePropValue=null;gwt.__getPropMap=null;gwt.__installRunAsyncCode=function(){};gwt.__gwtStartLoadingFragment=function(){return null};gwt.__gwt_isKnownPropertyValue=function(){return false};gwt.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};gwt.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[gwt.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
gwt.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(gwt.__errFn){n.onerror=function(){gwt.__errFn(S,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
gwt.__startLoadingFragment=function(a){return D(a)};gwt.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,bb);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;gwt.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return gwt.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){return o.appProfile};i[Kb]={jiva:V,sankhya:W};j[Lb]=function(){if(o.devicePixelRatio==Mb)return Nb;return Ob};i[Lb]={normal:V,retina:W};j[Pb]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(Qb)!=-1}())return Rb;if(function(){return a.indexOf(Sb)!=-1&&(b>=Tb&&b<Ub)}())return Vb;if(function(){return a.indexOf(Sb)!=-1&&(b>=Wb&&b<Ub)}())return Xb;if(function(){return a.indexOf(Sb)!=-1&&(b>=Yb&&b<Ub)}())return Zb;if(function(){return a.indexOf($b)!=-1||b>=Ub}())return _b;return bb};i[Pb]={gecko1_8:V,ie10:W,ie8:Mb,ie9:ac,safari:bc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};gwt.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};gwt.__computePropValue=k;o.__gwt_activeModules[S].bindings=gwt.__getPropMap;r(O,cc);if(q()){return D(dc)}var l;try{h([ec,Nb,Rb],fc);h([gc,Ob,Xb],hc);h([ec,Ob,Xb],hc);h([gc,Ob,Xb],hc+ic);h([ec,Ob,Xb],hc+ic);h([gc,Ob,Rb],jc);h([ec,Ob,Rb],jc);h([gc,Ob,Rb],jc+ic);h([ec,Ob,Rb],jc+ic);h([gc,Ob,Vb],kc);h([ec,Ob,Vb],kc);h([gc,Ob,Vb],kc+ic);h([ec,Ob,Vb],kc+ic);h([gc,Nb,Rb],lc);h([gc,Ob,Zb],mc);h([ec,Ob,Zb],mc);h([gc,Ob,Zb],mc+ic);h([ec,Ob,Zb],mc+ic);h([gc,Ob,_b],nc);h([ec,Ob,_b],nc);h([gc,Ob,_b],nc+ic);h([ec,Ob,_b],nc+ic);l=f[k(Kb)][k(Lb)][k(Pb)];var m=l.indexOf(oc);if(m!=-1){g=parseInt(l.substring(m+W),Tb);l=l.substring(V,m)}}catch(a){}gwt.__softPermutationId=g;return D(l+pc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(qc);b.setAttribute(rc,sc);b.setAttribute(tc,D(a));p.getElementsByTagName(ob)[V].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(uc,P);c(vc);c(wc);c(xc);c(yc);c(zc);c(Ac);c(Bc);c(Cc);r(uc,Dc)}
B();gwt.__moduleBase=C();t[S].moduleBase=gwt.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==Ec||o.location.protocol==Fc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=Gc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=Hc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Ic+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+Jc]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,Dc);A(H);return true}
gwt.succeeded=gwt();